services:
  - type: web
    name: n8n-service
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "seu_usuario"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "sua_senha"
      - key: N8N_HOST
        value: "0.0.0.0"
      - key: N8N_PORT
        value: "10000"
      - key: WEBHOOK_TUNNEL_URL
        value: "https://seu-dominio-do-render.onrender.com/"
      - key: DB_TYPE
        value: "postgresdb"
      - key: DB_POSTGRESDB_HOST
        value: "seu_host_neon"
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: DB_POSTGRESDB_DATABASE
        value: "seu_banco_neon"
      - key: DB_POSTGRESDB_USER
        value: "seu_usuario_neon"
      - key: DB_POSTGRESDB_PASSWORD
        value: "sua_senha_neon"
      - key: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
        value: "false"
