services:
  - type: web
    name: n8n-1
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "n8n start"
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "seuusuario"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "suasenha"
      - key: DB_TYPE
        value: "postgresdb"
      - key: DB_POSTGRESDB_HOST
        value: "ep-plain-fire-acfan4ne-pooler.sa-east-1.aws.neon.tech"
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: DB_POSTGRESDB_DATABASE
        value: "neondb"
      - key: DB_POSTGRESDB_USER
        value: "neondb_owner"
      - key: DB_POSTGRESDB_PASSWORD
        value: "npg_Thd7qMaDu2lk"
      - key: DB_POSTGRESDB_SSL_CA
        value: "-----BEGIN CERTIFICATE-----\n...certificado...\n-----END CERTIFICATE-----"
      - key: N8N_HOST
        value: "0.0.0.0"
      - key: N8N_PORT
        value: "3000"
