services:
  - type: web
    name: n8n-1
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "admin"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "SUA_SENHA_AQUI"
      - key: N8N_HOST
        value: "seu-dominio-do-render.onrender.com"
      - key: N8N_PORT
        value: "10000"
      - key: N8N_PROTOCOL
        value: "https"
      - key: DB_TYPE
        value: "postgresdb"
      - key: DB_POSTGRESDB_HOST
        value: "ep-plain-fire-acfan4ne-pooler.sa-east-1.aws.neon.tech"
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: DB_POSTGRESDB_DATABASE
        value: "neondb"
      - key: DB_POSTGRESDB_USER
        value: "neondb_owner"
      - key: DB_POSTGRESDB_PASSWORD
        value: "SUA_SENHA_DO_NEON"
      - key: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
        value: "false"
