services:
  - type: web
    name: n8n-miguel-1
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "n8n start"
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "william.crispimm@gmail.com"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "@Miguelbott1"
      - key: N8N_HOST
        value: "0.0.0.0"
      - key: N8N_PORT
        value: "10000"
      - key: N8N_ENCRYPTION_KEY
        value: "fehZJSoRoudIQeScPINnCk8piLEktphv" 
      - key: WEBHOOK_TUNNEL_URL
        value: "https://miguel-n8n-1.onrender.com/"
      - key: DB_TYPE
        value: "postgresdb"
      - key: DB_POSTGRESDB_HOST
        value: "ep-plain-fire-acfan4ne-pooler.sa-east-1.aws.neon.tech"
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: DB_POSTGRESDB_DATABASE
        value: "neondb"
      - key: DB_POSTGRESDB_USER
        value: "neondb_owner"
      - key: DB_POSTGRESDB_PASSWORD
        value: "npg_Thd7qMaDu2lk"
      - key: DB_POSTGRESDB_SCHEMA
        value: "public"
      - key: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
        value: "false"
      - key: DB_POSTGRESDB_SSL
        value: "true"
      - key: TELEGRAM_BOT_TOKEN
        value: "8211404971:AAEkpROe1nKMwN5iSqO3_pJqhlqkW3a8AsU"
      - key: TELEGRAM_ADMIN_CHAT_ID
        value: "8273258735"
      - key: RENDER1_URL
        value: "https://miguel-render-1.onrender.com"
      - key: SVC3_URL
        value: "https://miguel-n8n-keepalive-orchestrator.onrender.com"
      - key: SVC3_SRC
        value: "n8n1"
